// <auto-generated />
using System;
using MatchMasterWEB.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MatchMasterWEB.Migrations
{
    [DbContext(typeof(MatchMasterMySqlDatabaseContext))]
    [Migration("20240226115631_ChangeCityToCityID")]
    partial class ChangeCityToCityID
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MatchMasterWEB.Database.DB_Models.Fixture", b =>
                {
                    b.Property<int>("FixtureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Temperature")
                        .HasColumnType("double");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time(6)");

                    b.HasKey("FixtureId");

                    b.ToTable("Fixtures");
                });

            modelBuilder.Entity("MatchMasterWEB.Database.DB_Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("MatchMasterWEB.Database.DB_Models.PlayerStat", b =>
                {
                    b.Property<int>("StatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DribblingAttempts")
                        .HasColumnType("int");

                    b.Property<int>("DribblingSuccess")
                        .HasColumnType("int");

                    b.Property<int>("DuelsTotal")
                        .HasColumnType("int");

                    b.Property<int>("DuelsWon")
                        .HasColumnType("int");

                    b.Property<int>("FixtureId")
                        .HasColumnType("int");

                    b.Property<int>("FoulsCommitted")
                        .HasColumnType("int");

                    b.Property<int>("PassingAccuracy")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<double>("Rating")
                        .HasColumnType("double");

                    b.Property<int>("ShotsOnTarget")
                        .HasColumnType("int");

                    b.Property<int>("TotalShots")
                        .HasColumnType("int");

                    b.Property<int>("TotalTackles")
                        .HasColumnType("int");

                    b.HasKey("StatId");

                    b.HasIndex("FixtureId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerStats");
                });

            modelBuilder.Entity("MatchMasterWEB.Database.DB_Models.PlayerStat", b =>
                {
                    b.HasOne("MatchMasterWEB.Database.DB_Models.Fixture", "Fixture")
                        .WithMany("PlayerStats")
                        .HasForeignKey("FixtureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MatchMasterWEB.Database.DB_Models.Player", "Player")
                        .WithMany("PlayerStats")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fixture");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MatchMasterWEB.Database.DB_Models.Fixture", b =>
                {
                    b.Navigation("PlayerStats");
                });

            modelBuilder.Entity("MatchMasterWEB.Database.DB_Models.Player", b =>
                {
                    b.Navigation("PlayerStats");
                });
#pragma warning restore 612, 618
        }
    }
}
